import "../constants";
import {
  AWAITING_DOCS,
  AWAITING_PRE_PAYMENT,
  ORIG_DOC_SUBMISSION,
  RECEIVED_FILE,
  TRANSACTION_COMPLETED,
  TSR_SUBMISSION,
} from "../constants";

export const menuItems = [
  RECEIVED_FILE,
  AWAITING_DOCS,
  AWAITING_PRE_PAYMENT,
  TSR_SUBMISSION,
  TRANSACTION_COMPLETED,
  ORIG_DOC_SUBMISSION,
];
